#lang info

;; Package metadata.
(define version "0.2")
(define deps '("base"))
(define license 'MIT)

(define collection "drracket-catppuccin")

;; Catppuccin goes Purrr! 

	(define mocha-rosewater    #(245 224 220))
	(define mocha-flamingo     #(242 205 205))
	(define mocha-pink         #(245 194 231))
	(define mocha-mauve        #(203 166 247))
	(define mocha-red          #(243 139 168))
	(define mocha-maroon       #(235 160 172))
	(define mocha-peach        #(250 179 135))
	(define mocha-yellow       #(249 226 175))
	(define mocha-green        #(166 227 161))
	(define mocha-teal         #(148 226 213))
	(define mocha-sky          #(137 220 235))
	(define mocha-sapphire     #(116 199 236))
	(define mocha-blue         #(135 176 249))
	(define mocha-lavender     #(180 190 254))
	(define mocha-text         #(198 208 245))
	(define mocha-subtext1     #(179 188 223))
	(define mocha-subtext0     #(161 168 201))
	(define mocha-overlay2     #(142 149 179))
	(define mocha-overlay1     #(123 129 157))
	(define mocha-overlay0     #(105 109 134))
	(define mocha-surface2     #(86 89 112))
	(define mocha-surface1     #(67 70 90))
	(define mocha-surface0     #(49 50 68))
	(define mocha-base         #(30 30 46))
	(define mocha-mantle       #(24 24 37))
	(define mocha-crust        #(17 17 27))
	(define latte-rosewater #(222 149 132))
	(define frappe-rosewater #(242 213 207))
	(define macchiato-rosewater #(244 219 214))
	(define latte-flamingo #(221 120 120))
	(define frappe-flamingo #(238 190 190))
	(define macchiato-flamingo #(240 198 198))
	(define latte-pink #(236 131 208))
	(define frappe-pink #(244 184 228))
	(define macchiato-pink #(245 189 230))
	(define latte-mauve #(136 57 239))
	(define frappe-mauve #(202 158 230))
	(define macchiato-mauve #(198 160 246))
	(define latte-red #(210 15 57))
	(define frappe-red #(231 130 132))
	(define macchiato-red #(237 135 150))
	(define latte-maroon #(230 69 83))
	(define frappe-maroon #(234 153 156))
	(define macchiato-maroon #(238 153 160))
	(define latte-peach #(254 100 11))
	(define frappe-peach #(239 159 118))
	(define macchiato-peach #(245 169 127))
	(define latte-yellow #(228 147 32))
	(define frappe-yellow #(229 200 144))
	(define macchiato-yellow #(238 212 159))
	(define latte-green #(64 160 43))
	(define frappe-green #(166 209 137))
	(define macchiato-green #(166 218 149))
	(define latte-teal #(23 146 153))
	(define frappe-teal #(129 200 190))
	(define macchiato-teal #(139 213 202))
	(define latte-sky #(4 165 229))
	(define frappe-sky #(153 209 219))
	(define macchiato-sky #(145 215 227))
	(define latte-sapphire #(32 159 181))
	(define frappe-sapphire #(133 193 220))
	(define macchiato-sapphire #(125 196 228))
	(define latte-blue #(42 110 245))
	(define frappe-blue #(140 170 238))
	(define macchiato-blue #(138 173 244))
	(define latte-lavender #(114 135 253))
	(define frappe-lavender #(186 187 241))
	(define macchiato-lavender #(183 189 248))
	(define latte-text #(76 79 105))
	(define frappe-text #(198 206 239))
	(define macchiato-text #(197 207 245))
	(define latte-subtext1 #(92 95 119))
	(define frappe-subtext1 #(181 189 220))
	(define macchiato-subtext1 #(179 188 224))
	(define latte-subtext0 #(108 111 133))
	(define frappe-subtext0 #(165 172 201))
	(define macchiato-subtext0 #(161 170 203))
	(define latte-overlay2 #(124 127 147))
	(define frappe-overlay2 #(148 155 183))
	(define macchiato-overlay2 #(143 151 183))
	(define latte-overlay1 #(140 143 161))
	(define frappe-overlay1 #(131 138 164))
	(define macchiato-overlay1 #(125 132 162))
	(define latte-overlay0 #(156 160 176))
	(define frappe-overlay0 #(115 120 145))
	(define macchiato-overlay0 #(108 114 141))
	(define latte-surface2 #(172 176 190))
	(define frappe-surface2 #(98 103 126))
	(define macchiato-surface2 #(90 95 120))
	(define latte-surface1 #(188 192 204))
	(define frappe-surface1 #(81 86 108))
	(define macchiato-surface1 #(72 76 100))
	(define latte-surface0 #(204 208 218))
	(define frappe-surface0 #(65 69 89))
	(define macchiato-surface0 #(54 58 79))
	(define latte-base #(239 241 245))
	(define frappe-base #(48 52 70))
	(define macchiato-base #(36 39 58))
	(define latte-mantle #(230 233 239))
	(define frappe-mantle #(41 44 60))
	(define macchiato-mantle #(30 32 48))
	(define latte-crust #(220 224 232))
	(define frappe-crust #(35 38 52))
	(define macchiato-crust #(24 25 38))

  
;; Palettes:  Latte, Frappe, Macchiato, Mocha.
(define framework:color-schemes
  `(#hash((name . "Catppuccin Latte")
          (white-on-black-base? . #f)
          (colors
           .
	   ((drracket:error-background-highlighting                             ,latte-red)
            (drracket:language-name-and-memory-use-at-top-of-interactions ,latte-green)
            (framework:basic-canvas-background                            ,latte-base)
            (framework:default-text-color                                 ,latte-text)
            (framework:line-numbers                                       ,latte-subtext1)
            (framework:line-numbers-current-line-number-background        ,latte-surface2)
            (framework:line-numbers-current-line-number-foreground        ,latte-base)
            (framework:line-numbers-when-word-wrapping                    ,latte-base)
            (framework:misspelled-text-color                              ,latte-text)
            (framework:paren-match-color                                  ,latte-surface2)
            (framework:program-contour-current-location-bar               ,latte-lavender)
            (drracket:check-syntax:both-obligation-style-pref             ,latte-rosewater)
            (drracket:check-syntax:free-variable                          ,latte-red)
            (drracket:check-syntax:imported                               ,latte-mauve)
            (drracket:check-syntax:lexically-bound                        ,latte-sapphire)
            (drracket:check-syntax:my-obligation-style-pref               ,latte-red)
            (drracket:check-syntax:set!d                                  ,latte-red)
            (drracket:check-syntax:their-obligation-style-pref            ,latte-green)
            (drracket:check-syntax:unk-obligation-style-pref              ,latte-text)
            (drracket:check-syntax:unused-require                         ,latte-red)
            (drracket:read-eval-print-loop:error-color                    ,latte-red)
            (drracket:read-eval-print-loop:out-color                      ,latte-green)
            (drracket:read-eval-print-loop:value-color                    ,latte-blue)
            (drracket:syncheck:document-identifier                        ,latte-overlay0)
            (drracket:syncheck:matching-identifiers                       ,latte-rosewater)
            (drracket:syncheck:tail-arrow                                 ,latte-rosewater)
            (drracket:syncheck:template-arrow                             ,latte-rosewater)
            (drracket:syncheck:untacked                                   ,latte-peach)
            (drracket:syncheck:unused-identifier                          ,latte-rosewater)
            (drracket:syncheck:var-arrow                                  ,latte-blue)
            (stepper:redex-highlight-color                                ,latte-green)
            (stepper:reduct-highlight-color                               ,latte-blue)
            (drracket:check-syntax:both-obligation-style-pref             ,latte-rosewater)
            (framework:syntax-color:scheme:comment                        ,latte-surface2)
            (framework:syntax-color:scheme:constant                       ,latte-peach)
            (framework:syntax-color:scheme:error                          ,latte-red)
            (framework:syntax-color:scheme:hash-colon-keyword             ,latte-peach)
            (framework:syntax-color:scheme:keyword                        ,latte-mauve)
            (framework:syntax-color:scheme:other                          ,latte-text)
            (framework:syntax-color:scheme:parenthesis                    ,latte-mauve)
            (framework:syntax-color:scheme:string                         ,latte-green)
            (framework:syntax-color:scheme:symbol                         ,latte-blue)
            (framework:syntax-color:scheme:text                           ,latte-green)
            (plt:htdp:test-coverage-off                                   ,latte-red)
            (plt:htdp:test-coverage-on                                    ,latte-text)
            (plt:module-language:test-coverage-off                        ,latte-red)
            (plt:module-language:test-coverage-on                         ,latte-text))))

  #hash((name . "Catppuccin Frappe")
          (white-on-black-base? . #t)
          (colors
           .
	   ((drracket:error-background-highlighting                             ,frappe-red)
            (drracket:language-name-and-memory-use-at-top-of-interactions ,frappe-green)
            (framework:basic-canvas-background                            ,frappe-base)
            (framework:default-text-color                                 ,frappe-text)
            (framework:line-numbers                                       ,frappe-subtext1)
            (framework:line-numbers-current-line-number-background        ,frappe-surface2)
            (framework:line-numbers-current-line-number-foreground        ,frappe-crust)
            (framework:line-numbers-when-word-wrapping                    ,frappe-base)
            (framework:misspelled-text-color                              ,frappe-text)
            (framework:paren-match-color                                  ,frappe-surface2)
            (framework:program-contour-current-location-bar               ,frappe-lavender)
            (drracket:check-syntax:both-obligation-style-pref             ,frappe-rosewater)
            (drracket:check-syntax:free-variable                          ,frappe-red)
            (drracket:check-syntax:imported                               ,frappe-mauve)
            (drracket:check-syntax:lexically-bound                        ,frappe-sapphire)
            (drracket:check-syntax:my-obligation-style-pref               ,frappe-red)
            (drracket:check-syntax:set!d                                  ,frappe-red)
            (drracket:check-syntax:their-obligation-style-pref            ,frappe-green)
            (drracket:check-syntax:unk-obligation-style-pref              ,frappe-text)
            (drracket:check-syntax:unused-require                         ,frappe-red)
            (drracket:read-eval-print-loop:error-color                    ,frappe-red)
            (drracket:read-eval-print-loop:out-color                      ,frappe-green)
            (drracket:read-eval-print-loop:value-color                    ,frappe-blue)
            (drracket:syncheck:document-identifier                        ,frappe-crust)
            (drracket:syncheck:matching-identifiers                       ,frappe-rosewater)
            (drracket:syncheck:tail-arrow                                 ,frappe-rosewater)
            (drracket:syncheck:template-arrow                             ,frappe-rosewater)
            (drracket:syncheck:untacked                                   ,frappe-peach)
            (drracket:syncheck:unused-identifier                          ,frappe-rosewater)
            (drracket:syncheck:var-arrow                                  ,frappe-blue)
            (stepper:redex-highlight-color                                ,frappe-green)
            (stepper:reduct-highlight-color                               ,frappe-blue)
            (drracket:check-syntax:both-obligation-style-pref             ,frappe-rosewater)
            (framework:syntax-color:scheme:comment                        ,frappe-surface2)
            (framework:syntax-color:scheme:constant                       ,frappe-peach)
            (framework:syntax-color:scheme:error                          ,frappe-red)
            (framework:syntax-color:scheme:hash-colon-keyword             ,frappe-peach)
            (framework:syntax-color:scheme:keyword                        ,frappe-mauve)
            (framework:syntax-color:scheme:other                          ,frappe-text)
            (framework:syntax-color:scheme:parenthesis                    ,frappe-mauve)
            (framework:syntax-color:scheme:string                         ,frappe-green)
            (framework:syntax-color:scheme:symbol                         ,frappe-blue)
            (framework:syntax-color:scheme:text                           ,frappe-green)
            (plt:htdp:test-coverage-off                                   ,frappe-red)
            (plt:htdp:test-coverage-on                                    ,frappe-text)
            (plt:module-language:test-coverage-off                        ,frappe-red)
            (plt:module-language:test-coverage-on                         ,frappe-text))))

  #hash((name . "Catppuccin Macchiato")
          (white-on-black-base? . #t)
          (colors
           .
	   ((drracket:error-background-highlighting                             ,macchiato-red)
            (drracket:language-name-and-memory-use-at-top-of-interactions ,macchiato-green)
            (drracket:syncheck:matching-identifiers                       ,macchiato-crust) ;; <-- doesn't work!
            (framework:basic-canvas-background                            ,macchiato-base)
            (framework:default-text-color                                 ,macchiato-text)
            (framework:line-numbers                                       ,macchiato-subtext1)
            (framework:line-numbers-current-line-number-background        ,macchiato-surface2)
            (framework:line-numbers-current-line-number-foreground        ,macchiato-crust)
            (framework:line-numbers-when-word-wrapping                    ,macchiato-base)
            (framework:misspelled-text-color                              ,macchiato-text)
            (framework:paren-match-color                                  ,macchiato-surface2)
            (framework:program-contour-current-location-bar               ,macchiato-lavender)
            (drracket:check-syntax:both-obligation-style-pref             ,macchiato-rosewater)
            (drracket:check-syntax:free-variable                          ,macchiato-red)
            (drracket:check-syntax:imported                               ,macchiato-mauve)
            (drracket:check-syntax:lexically-bound                        ,macchiato-sapphire)
            (drracket:check-syntax:my-obligation-style-pref               ,macchiato-red)
            (drracket:check-syntax:set!d                                  ,macchiato-red)
            (drracket:check-syntax:their-obligation-style-pref            ,macchiato-green)
            (drracket:check-syntax:unk-obligation-style-pref              ,macchiato-text)
            (drracket:check-syntax:unused-require                         ,macchiato-red)
            (drracket:read-eval-print-loop:error-color                    ,macchiato-red)
            (drracket:read-eval-print-loop:out-color                      ,macchiato-green)
            (drracket:read-eval-print-loop:value-color                    ,macchiato-blue)
            (drracket:syncheck:document-identifier                        ,macchiato-crust)
            (drracket:syncheck:matching-identifiers                       ,macchiato-rosewater)
            (drracket:syncheck:tail-arrow                                 ,macchiato-rosewater)
            (drracket:syncheck:template-arrow                             ,macchiato-rosewater)
            (drracket:syncheck:untacked                                   ,macchiato-peach)
            (drracket:syncheck:unused-identifier                          ,macchiato-rosewater)
            (drracket:syncheck:var-arrow                                  ,macchiato-blue)
            (stepper:redex-highlight-color                                ,macchiato-green)
            (stepper:reduct-highlight-color                               ,macchiato-blue)
            (drracket:check-syntax:both-obligation-style-pref             ,macchiato-rosewater)
            (framework:syntax-color:scheme:comment                        ,macchiato-surface2)
            (framework:syntax-color:scheme:constant                       ,macchiato-peach)
            (framework:syntax-color:scheme:error                          ,macchiato-red)
            (framework:syntax-color:scheme:hash-colon-keyword             ,macchiato-peach)
            (framework:syntax-color:scheme:keyword                        ,macchiato-mauve)
            (framework:syntax-color:scheme:other                          ,macchiato-text)
            (framework:syntax-color:scheme:parenthesis                    ,macchiato-mauve)
            (framework:syntax-color:scheme:string                         ,macchiato-green)
            (framework:syntax-color:scheme:symbol                         ,macchiato-blue)
            (framework:syntax-color:scheme:text                           ,macchiato-green)
            (plt:htdp:test-coverage-off                                   ,macchiato-red)
            (plt:htdp:test-coverage-on                                    ,macchiato-text)
            (plt:module-language:test-coverage-off                        ,macchiato-red)
            (plt:module-language:test-coverage-on                         ,macchiato-text))))

  #hash((name . "Catppuccin Mocha")
          (white-on-black-base? . #t)
          (colors
           .
	   ((drracket:error-background-highlighting                             ,mocha-red)
            (drracket:language-name-and-memory-use-at-top-of-interactions ,mocha-green)
            (framework:basic-canvas-background                            ,mocha-base)
            (framework:default-text-color                                 ,mocha-text)
            (framework:line-numbers                                       ,mocha-subtext1)
            (framework:line-numbers-current-line-number-background        ,mocha-text)
            (framework:line-numbers-current-line-number-foreground        ,mocha-crust)
            (framework:line-numbers-when-word-wrapping                    ,mocha-base)
            (framework:misspelled-text-color                              ,mocha-text)
            (framework:paren-match-color                                  ,mocha-surface2)
            (framework:program-contour-current-location-bar               ,mocha-lavender)
            (drracket:check-syntax:both-obligation-style-pref             ,mocha-rosewater)
            (drracket:check-syntax:free-variable                          ,mocha-red)
            (drracket:check-syntax:imported                               ,mocha-mauve)
            (drracket:check-syntax:lexically-bound                        ,mocha-sapphire)
            (drracket:check-syntax:my-obligation-style-pref               ,mocha-red)
            (drracket:check-syntax:set!d                                  ,mocha-red)
            (drracket:check-syntax:their-obligation-style-pref            ,mocha-green)
            (drracket:check-syntax:unk-obligation-style-pref              ,mocha-text)
            (drracket:check-syntax:unused-require                         ,mocha-red)
            (drracket:read-eval-print-loop:error-color                    ,mocha-red)
            (drracket:read-eval-print-loop:out-color                      ,mocha-green)
            (drracket:read-eval-print-loop:value-color                    ,mocha-blue)
            (drracket:syncheck:document-identifier                        ,mocha-crust)
            (drracket:syncheck:matching-identifiers                       ,mocha-rosewater)
            (drracket:syncheck:tail-arrow                                 ,mocha-rosewater)
            (drracket:syncheck:template-arrow                             ,mocha-rosewater)
            (drracket:syncheck:untacked                                   ,mocha-peach)
            (drracket:syncheck:unused-identifier                          ,mocha-rosewater)
            (drracket:syncheck:var-arrow                                  ,mocha-blue)
            (stepper:redex-highlight-color                                ,mocha-green)
            (stepper:reduct-highlight-color                               ,mocha-blue)
            (drracket:check-syntax:both-obligation-style-pref             ,mocha-rosewater)
            (framework:syntax-color:scheme:comment                        ,mocha-surface2)
            (framework:syntax-color:scheme:constant                       ,mocha-peach)
            (framework:syntax-color:scheme:error                          ,mocha-red)
            (framework:syntax-color:scheme:hash-colon-keyword             ,mocha-peach)
            (framework:syntax-color:scheme:keyword                        ,mocha-mauve)
            (framework:syntax-color:scheme:other                          ,mocha-text)
            (framework:syntax-color:scheme:parenthesis                    ,mocha-mauve)
            (framework:syntax-color:scheme:string                         ,mocha-green)
            (framework:syntax-color:scheme:symbol                         ,mocha-blue)
            (framework:syntax-color:scheme:text                           ,mocha-green)
            (plt:htdp:test-coverage-off                                   ,mocha-red)
            (plt:htdp:test-coverage-on                                    ,mocha-text)
            (plt:module-language:test-coverage-off                        ,mocha-red)
            (plt:module-language:test-coverage-on                         ,mocha-text))))

    ))
